<a href="https://colab.research.google.com/github/meltyyyyy/kaggle-amex/blob/main/Notebooks/Starter/EDA001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Config:
    name = "Starter/EDA001"

    n_splits = 5
    n_neighbors = 10
    seed = 2022
    target = "target"

    # Colab Env
    upload_from_colab = True
    api_path = "/content/drive/MyDrive/workspace/kaggle.json"
    drive_path = "/content/drive/MyDrive/workspace/kaggle-amex"
    
    # Kaggle Env
    kaggle_dataset_path = None

In [2]:
import os
import json
import warnings
import shutil
import logging
import joblib
import random
import datetime
import sys
import gc
import multiprocessing
import joblib
import pickle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm.auto import tqdm
warnings.filterwarnings('ignore')

In [3]:
COLAB = "google.colab" in sys.modules
if COLAB:
    print("This environment is Google Colab")
    
    # mount
    from google.colab import drive
    if not os.path.isdir("/content/drive"):
        drive.mount('/content/drive') 
	
    # import library
    # ! pip install lightgbm==3.3.1
    # ! pip install --quiet iterative-stratification
    # ! pip install --quiet tensorflow-addons

    # use kaggle api (need kaggle token)
    f = open(Config.api_path, 'r')
    json_data = json.load(f) 
    os.environ["KAGGLE_USERNAME"] = json_data["username"]
    os.environ["KAGGLE_KEY"] = json_data["key"]
    
    # set dirs
    DRIVE = Config.drive_path
    EXP = (Config.name if Config.name is not None 
           else get("http://172.28.0.2:9000/api/sessions").json()[0]["name"][:-6])
    INPUT = os.path.join(DRIVE, "Input")
    OUTPUT = os.path.join(DRIVE, "Output")
    SUBMISSION = os.path.join(DRIVE, "Submission")
    OUTPUT_EXP = os.path.join(OUTPUT, EXP) 
    EXP_MODEL = os.path.join(OUTPUT_EXP, "model")
    EXP_FIG = os.path.join(OUTPUT_EXP, "fig")
    EXP_PREDS = os.path.join(OUTPUT_EXP, "preds")

    # make dirs
    for d in [INPUT, SUBMISSION, EXP_MODEL, EXP_FIG, EXP_PREDS]:
        os.makedirs(d, exist_ok=True)

    if not os.path.isfile(os.path.join(INPUT, "amex-default-prediction.zip")):
        # load dataset
        ! kaggle competitions download -c amex-default-prediction -p $INPUT 
else:
    print("This environment is Kaggle Kernel")
    
    # set dirs
    INPUT = "../input/amex-default-prediction"
    EXP, OUTPUT, SUBMISSION = "./", "./", "./"
    EXP_MODEL = os.path.join(EXP, "model")
    EXP_FIG = os.path.join(EXP, "fig")
    EXP_PREDS = os.path.join(EXP, "preds")
    
    # copy dirs
    if Config.kaggle_dataset_path is not None:
        KD_MODEL = os.path.join(Config.kaggle_dataset_path, "model")
        KD_EXP_PREDS = os.path.join(Config.kaggle_dataset_path, "preds")
        shutil.copytree(KD_MODEL, EXP_MODEL)
        shutil.copytree(KD_EXP_PREDS, EXP_PREDS)

    # make dirs
    for d in [EXP_MODEL, EXP_FIG, EXP_PREDS]:
        os.makedirs(d, exist_ok=True)


This environment is Google Colab
Mounted at /content/drive


In [4]:
%%time
train = pd.read_csv(os.path.join(INPUT, 'train_data.csv') if COLAB else 'train_data.csv')

CPU times: user 3min 3s, sys: 40.7 s, total: 3min 43s
Wall time: 4min 8s


In [5]:
train.head()

customer_ID         S_2       P_2  \
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-03-09  0.938469   
1  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-04-07  0.936665   
2  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-05-28  0.954180   
3  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-06-13  0.960384   
4  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-07-16  0.947248   

       D_39       B_1       B_2       R_1       S_3      D_41       B_3  ...  \
0  0.001733  0.008724  1.006838  0.009228  0.124035  0.008771  0.004709  ...   
1  0.005775  0.004923  1.000653  0.006151  0.126750  0.000798  0.002714  ...   
2  0.091505  0.021655  1.009672  0.006815  0.123977  0.007598  0.009423  ...   
3  0.002455  0.013683  1.002700  0.001373  0.117169  0.000685  0.005531  ...   
4  0.002483  0.015193  1.000727  0.007605  0.117325  0.004653  0.009312  ...   

   D_136  D_137  D_138     D_139     D_140     D_141  D_142     D_143  \
0    NaN    NaN    NaN  0.002427  0.003706  0.003818    NaN  0.000569   
1    NaN    NaN    NaN  0.003954  0.003167  0.005032    NaN  0.009576   
2    NaN    NaN    NaN  0.003269  0.007329  0.000427    NaN  0.003429   
3    NaN    NaN    NaN  0.006117  0.004516  0.003200    NaN  0.008419   
4    NaN    NaN    NaN  0.003671  0.004946  0.008889    NaN  0.001670   

      D_144     D_145  
0  0.000610  0.002674  
1  0.005492  0.009217  
2  0.006986  0.002603  
3  0.006527  0.009600  
4  0.008126  0.009827  

[5 rows x 190 columns]

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: float64(185), int64(1), object(4)
memory usage: 7.8+ GB


### Reduce memory usage by converting float64 to float16.

In [11]:
# https://www.kaggle.com/code/balabaskar/memory-reduction-using-pandas
float_cols = [col for col in train.columns if train[col].dtype == 'float64']
int_cols = [col for col in train.columns if train[col].dtype == 'int64']
len(float_cols), print(int_cols)

['B_31']


(185, None)

In [21]:
for col in float_cols:
    train[col] = train[col].astype('float16')

Sucessfully reduced memory from 7.8GB to 2.1GB

In [22]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: float16(185), int64(1), object(4)
memory usage: 2.1+ GB


### Reduce memory usage by converting int64 to int8.

In [25]:
train['B_31'].unique()

array([1, 0])

It seems there's no problem for converting it to int8.

In [26]:
train['B_31'] = train['B_31'].astype('int8')

It does not change memory usege.

In [27]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: float16(185), int8(1), object(4)
memory usage: 2.1+ GB


### Look at categorycal features

In [29]:
cat_cols = ['B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']
train[cat_cols].head()

B_30  B_38  D_114  D_116  D_117  D_120  D_126 D_63 D_64  D_66  D_68
0   0.0   2.0    1.0    0.0    4.0    0.0    1.0   CR    O   NaN   6.0
1   0.0   2.0    1.0    0.0    4.0    0.0    1.0   CR    O   NaN   6.0
2   0.0   2.0    1.0    0.0    4.0    0.0    1.0   CR    O   NaN   6.0
3   0.0   2.0    1.0    0.0    4.0    0.0    1.0   CR    O   NaN   6.0
4   0.0   2.0    1.0    0.0    4.0    0.0    1.0   CR    O   NaN   6.0

In [30]:
train['B_30'].unique()

array([ 0.,  2.,  1., nan], dtype=float16)

In [31]:
train['B_38'].unique()

array([ 2.,  1.,  3.,  5.,  6.,  7.,  4., nan], dtype=float16)

In [33]:
train['D_114'].unique()

array([ 1.,  0., nan], dtype=float16)

In [35]:
train['D_116'].unique()

array([ 0., nan,  1.], dtype=float16)

In [36]:
train['D_117'].unique()

array([ 4., -1.,  6.,  2.,  1., nan,  3.,  5.], dtype=float16)

In [37]:
train['D_120'].unique()

array([ 0.,  1., nan], dtype=float16)

In [38]:
train['D_126'].unique()

array([ 1., nan,  0., -1.], dtype=float16)

In [39]:
train['D_63'].unique()

array(['CR', 'CO', 'CL', 'XZ', 'XM', 'XL'], dtype=object)

In [40]:
train['D_64'].unique()

array(['O', 'R', nan, 'U', '-1'], dtype=object)

In [41]:
train['D_66'].unique()

array([nan,  1.,  0.], dtype=float16)

In [42]:
train['D_68'].unique()

array([ 6.,  2.,  3., nan,  5.,  4.,  0.,  1.], dtype=float16)

Now let's convert float16 features to categorical

In [44]:
for col in cat_cols:
    train[col] = train[col].astype('category')

In [45]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: category(11), float16(176), int8(1), object(2)
memory usage: 2.0+ GB


### Look at object features

In [46]:
obj_cols = [col for col in train.columns if train[col].dtype == 'object']
obj_cols

['customer_ID', 'S_2']

In [47]:
train[obj_cols].head()

customer_ID         S_2
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-03-09
1  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-04-07
2  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-05-28
3  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-06-13
4  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-07-16

https://www.kaggle.com/competitions/amex-default-prediction/data.  
It says 'S_' column is spend variables. Guessing this is a transaction date?  
D_* = Delinquency variables.  
S_* = Spend variables.  
P_* = Payment variables.  
B_* = Balance variables. 
R_* = Risk variables.  

In [48]:
train['customer_ID'].value_counts()

0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a    13
a3111280bfa1ed8fafd0b06839eb707f4538497e8087cb62958bb03e1bdde214    13
a31376930229162f886c091e5a56a528f81c10a523285828ed05a6e9ccf56722    13
a312c595dfaee96c8a597107d2754a49b1acfd127400d98991762d87837b1b65    13
a312aff722e7230f9d6a313ff777d6f00166c6bada21a333982426758a2e2a9d    13
                                                                    ..
a84839802f1f37a86a7fe34ddba4791d33d878df3937b509841def0a9e252748     1
01f4f7b14d83b6a8f88e4355279224615da083b19e3e5f15b98f274ced8cf752     1
eef07ea56302cebcd57374c6565bb3e5c7af856796d9cbc31ed42aa0fc73b7fc     1
d192480082e86e3b4da68f014b284f2a2624b45956eed279416c796de043b7ce     1
d9ea3cffff889b522a69bde89aee382dcff8bffe32c9a38653bdaa2ff4330041     1
Name: customer_ID, Length: 458913, dtype: int64

Some customers have multiple table. Let's look at what's going on.

In [50]:
train[train['customer_ID'] == '0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a']

customer_ID         S_2       P_2  \
0   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-03-09  0.938477   
1   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-04-07  0.936523   
2   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-05-28  0.954102   
3   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-06-13  0.960449   
4   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-07-16  0.947266   
5   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-08-04  0.945801   
6   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-09-18  0.940918   
7   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-10-08  0.914551   
8   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-11-20  0.950684   
9   0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-12-04  0.868652   
10  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2018-01-11  0.909668   
11  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2018-02-21  0.937500   
12  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2018-03-13  0.934570   

        D_39       B_1       B_2       R_1       S_3      D_41       B_3  ...  \
0   0.001734  0.008728  1.006836  0.009224  0.124023  0.008774  0.004707  ...   
1   0.005775  0.004925  1.000977  0.006153  0.126709  0.000798  0.002714  ...   
2   0.091492  0.021652  1.009766  0.006817  0.123962  0.007599  0.009422  ...   
3   0.002455  0.013687  1.002930  0.001372  0.117188  0.000685  0.005531  ...   
4   0.002483  0.015190  1.000977  0.007607  0.117310  0.004654  0.009308  ...   
5   0.001746  0.007866  1.004883  0.004219  0.110962  0.009857  0.009865  ...   
6   0.002182  0.018860  1.007812  0.004509  0.103333  0.006603  0.000783  ...   
7   0.003029  0.014328  1.000000  0.000263  0.108093  0.009529  0.007835  ...   
8   0.009895  0.016891  1.003906  0.001789  0.102783  0.002520  0.009819  ...   
9   0.001082  0.001930  1.007812  0.001772  0.100464  0.004627  0.006073  ...   
10  0.005714  0.002829  1.004883  0.008179  0.098877  0.001853  0.003239  ...   
11  0.002424  0.019836  1.008789  0.000607  0.102966  0.006172  0.007454  ...   
12  0.009117  0.009384  1.007812  0.006104  0.135010  0.001604  0.007175  ...   

    D_136  D_137  D_138     D_139     D_140     D_141  D_142     D_143  \
0     NaN    NaN    NaN  0.002426  0.003706  0.003819    NaN  0.000569   
1     NaN    NaN    NaN  0.003956  0.003166  0.005032    NaN  0.009575   
2     NaN    NaN    NaN  0.003269  0.007328  0.000427    NaN  0.003429   
3     NaN    NaN    NaN  0.006119  0.004517  0.003201    NaN  0.008423   
4     NaN    NaN    NaN  0.003672  0.004944  0.008888    NaN  0.001670   
5     NaN    NaN    NaN  0.001925  0.008598  0.004528    NaN  0.000674   
6     NaN    NaN    NaN  0.001336  0.004360  0.009384    NaN  0.007729   
7     NaN    NaN    NaN  0.002398  0.008453  0.005554    NaN  0.001831   
8     NaN    NaN    NaN  0.009743  0.003967  0.007942    NaN  0.008720   
9     NaN    NaN    NaN  0.003611  0.009605  0.007267    NaN  0.008766   
10    NaN    NaN    NaN  0.000427  0.004593  0.003613    NaN  0.007568   
11    NaN    NaN    NaN  0.001563  0.001976  0.002569    NaN  0.001099   
12    NaN    NaN    NaN  0.007187  0.004234  0.005085    NaN  0.005810   

       D_144     D_145  
0   0.000610  0.002674  
1   0.005493  0.009216  
2   0.006985  0.002604  
3   0.006527  0.009598  
4   0.008125  0.009827  
5   0.002222  0.002884  
6   0.007660  0.002224  
7   0.009613  0.007385  
8   0.004368  0.000996  
9   0.004753  0.009071  
10  0.003004  0.006363  
11  0.006348  0.004204  
12  0.002970  0.008530  

[13 rows x 190 columns]

This must be a withdrawal date.  
Now let's connvert S_2 to datetime, customer_id to string.

In [51]:
train['customer_ID'] = train['customer_ID'].astype('str')
train['S_2'] = pd.to_datetime(train['S_2'])

Minimum memory usage seems to be 2.0 GB.  
float32 -> float16.  
int64 -> int8.  

In [52]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: category(11), datetime64[ns](1), float16(176), int8(1), object(1)
memory usage: 2.0+ GB


to save as parquet for rapid reading, convert float16 to float32 since parquet does not accept half float.

In [61]:
for col in float_cols:
    train[col] = train[col].astype('float32')
for col in cat_cols:
    train[col] = train[col].astype('category')

In [62]:
train.to_parquet(os.path.join(INPUT, 'train.parquet'))

It significantly improved. 5 min to 5 seconds!

In [63]:
%%time
train = pd.read_parquet(os.path.join(INPUT, 'train.parquet') if COLAB else 'train.parquet')

CPU times: user 12.2 s, sys: 9.62 s, total: 21.8 s
Wall time: 5.1 s


In [64]:
train.head()

customer_ID        S_2       P_2  \
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f... 2017-03-09  0.938477   
1  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f... 2017-04-07  0.936523   
2  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f... 2017-05-28  0.954102   
3  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f... 2017-06-13  0.960449   
4  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f... 2017-07-16  0.947266   

       D_39       B_1       B_2       R_1       S_3      D_41       B_3  ...  \
0  0.001734  0.008728  1.006836  0.009224  0.124023  0.008774  0.004707  ...   
1  0.005775  0.004925  1.000977  0.006153  0.126709  0.000798  0.002714  ...   
2  0.091492  0.021652  1.009766  0.006817  0.123962  0.007599  0.009422  ...   
3  0.002455  0.013687  1.002930  0.001372  0.117188  0.000685  0.005531  ...   
4  0.002483  0.015190  1.000977  0.007607  0.117310  0.004654  0.009308  ...   

   D_136  D_137  D_138     D_139     D_140     D_141  D_142     D_143  \
0    NaN    NaN    NaN  0.002426  0.003706  0.003819    NaN  0.000569   
1    NaN    NaN    NaN  0.003956  0.003166  0.005032    NaN  0.009575   
2    NaN    NaN    NaN  0.003269  0.007328  0.000427    NaN  0.003429   
3    NaN    NaN    NaN  0.006119  0.004517  0.003201    NaN  0.008423   
4    NaN    NaN    NaN  0.003672  0.004944  0.008888    NaN  0.001670   

      D_144     D_145  
0  0.000610  0.002674  
1  0.005493  0.009216  
2  0.006985  0.002604  
3  0.006527  0.009598  
4  0.008125  0.009827  

[5 rows x 190 columns]

It seems some float categorical colmuns are converted to float64 when reading parquet.

In [65]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5531451 entries, 0 to 5531450
Columns: 190 entries, customer_ID to D_145
dtypes: category(2), datetime64[ns](1), float32(176), float64(9), int8(1), object(1)
memory usage: 4.1+ GB


In [66]:
del train